version: '3.9'

services:
  app:
    build: .
    container_name: form-engine-app
    restart: always
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/form_engine?schema=public'
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: form-engine-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: form_engine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
